<a href="https://colab.research.google.com/github/DainoraSvet/University-Things/blob/main/Python_Colab_Review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
from torch import nn # import torch.nn as nn

In [4]:
x = 5
y = 6
x, y = 5, 6 # same as in the top
x
print(x) # same as x

5


In [5]:
type(x)

int

In [6]:
def add_multiply_by_2(a, b):
  return 2*(a+b)

In [7]:
z = add_multiply_by_2(1, 2)

In [8]:
print(z)

6


In [29]:
class Network(nn.Module):
  def __init__(self, input_size=1): # self refers to the object itself
    super(Network, self).__init__() # subclass executes the initialization routine of the master class
    self.layer = nn.Linear(input_size, 1) # initialization for the class
    self.input_size = input_size
  def forward(self, x):
    x = self.layer(x)
    return x

In [30]:
model = Network(input_size=10)
print(model)

Network(
  (layer): Linear(in_features=10, out_features=1, bias=True)
)


In [31]:
model2 = Network()
print(model2)

Network(
  (layer): Linear(in_features=1, out_features=1, bias=True)
)


In [32]:
model.input_size

10

In [33]:
model2.input_size

1

In [34]:
input = torch.tensor(2.0).unsqueeze(0) # instead 2.0 we could write 2.
input

tensor([2.])

In [36]:
model2.forward(input)

tensor([0.3901], grad_fn=<ViewBackward0>)

In [37]:
model2(input)

tensor([0.3901], grad_fn=<ViewBackward0>)

In [40]:
for i in range(5):
  print(i)

0
1
2
3
4


In [41]:
if (i < 2):
  print("yes")
else:
  print("no")

no


In [43]:
print("yes") if (i < 2) else print ("no")

no


# How to Load file?

In [ ]:
# there is a cloud instance, it is load in cloud

In [2]:
import urllib.request
url = "https://www.worldatlas.com/animals/snake.html"
urllib.request.urlretrieve(url, 'shutterstock-1708408498.jpg')

('shutterstock-1708408498.jpg', <http.client.HTTPMessage at 0x7c37ec32d4e0>)